insert into MLIBUSER(username,passwordHash) values ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');
insert into USERS_GROUPS(username,roleid) values ('admin', 'ADMIN');

insert into MLIBUSER(username,passwordHash) values ('user', '04f8996da763b7a969b1028ee3007569eaf3a635486ddab211d512c85b9df8fb');
insert into USERS_GROUPS(username,roleid) values ('user', 'USER');

/* Inicializace tabulky Genre */
insert into GENRE(name) values ('Rock');
insert into GENRE(name) values ('Art Rock');
insert into GENRE(name) values ('Progressive Rock');
insert into GENRE(name) values ('Symphonic');
insert into GENRE(name) values ('Classical');
insert into GENRE(name) values ('Psychedelic');
insert into GENRE(name) values ('Indie Rock');
insert into GENRE(name) values ('Modern Rock');
insert into GENRE(name) values ('Punk');
insert into GENRE(name) values ('Punk Rock');
insert into GENRE(name) values ('Pop');
insert into GENRE(name) values ('Pop Rock');
insert into GENRE(name) values ('Ambient');
insert into GENRE(name) values ('Country');
insert into GENRE(name) values ('Dance');
insert into GENRE(name) values ('Trance');
insert into GENRE(name) values ('Disco');
insert into GENRE(name) values ('Techno');
insert into GENRE(name) values ('Electronic');
insert into GENRE(name) values ('R&B');
insert into GENRE(name) values ('Jazz');
insert into GENRE(name) values ('Reggae');
insert into GENRE(name) values ('Swing');
insert into GENRE(name) values ('Ska');
insert into GENRE(name) values ('World');
insert into GENRE(name) values ('Soundtrack');

/* Inicializace tabulky Artist */
insert into ARTIST(name) values ('Porcupine Tree');
insert into ARTIST(name) values ('Pink Floyd');
insert into ARTIST(name) values ('Rammstein');
insert into ARTIST(name) values ('Safri Duo');
insert into ARTIST(name) values ('Fatboy Slim');
insert into ARTIST(name) values ('Paul Van Dyk');
insert into ARTIST(name) values ('Gorillaz');
insert into ARTIST(name) values ('Moby');
insert into ARTIST(name) values ('Herbie Hancock');
insert into ARTIST(name) values ('The Who');
insert into ARTIST(name) values ('The Doors');
insert into ARTIST(name) values ('The Beatles');
insert into ARTIST(name) values ('Nirvana');
insert into ARTIST(name) values ('Foo Figters');
insert into ARTIST(name) values ('U2');
insert into ARTIST(name) values ('Led Zeppelin');
insert into ARTIST(name) values ('Rolling Stones');
insert into ARTIST(name) values ('Hans Zimmer');
insert into ARTIST(name) values ('Howard Shore');
insert into ARTIST(name) values ('John Williams');
insert into ARTIST(name) values ('David Arnold');
insert into ARTIST(name) values ('Trevor Jones');
insert into ARTIST(name) values ('BeatleJazz');
insert into ARTIST(name) values ('Jazz Q');
insert into ARTIST(name) values ('Frank Sinatra');
insert into ARTIST(name) values ('Edith Piaf');
insert into ARTIST(name) values ('Victor Wooten');
insert into ARTIST(name) values ('Billy Evans');
insert into ARTIST(name) values ('George Duke');
insert into ARTIST(name) values ('Oscar Peterson');
insert into ARTIST(name) values ('Chick Corea');
insert into ARTIST(name) values ('Stan Getz');
insert into ARTIST(name) values ('Count Basie');
insert into ARTIST(name) values ('Duke Ellington');
insert into ARTIST(name) values ('Saint Germain');
insert into ARTIST(name) values ('Glenn Miller');
insert into ARTIST(name) values ('Luis Armstrong');
insert into ARTIST(name) values ('Billie Holiday');
insert into ARTIST(name) values ('Buty');
insert into ARTIST(name) values ('Wohnout');
insert into ARTIST(name) values ('Sunshine');
insert into ARTIST(name) values ('-123min');
insert into ARTIST(name) values ('J.A.R.');
insert into ARTIST(name) values ('Antonio Vivaldi');
insert into ARTIST(name) values ('Peter Ilyich Tchaikovsky');
insert into ARTIST(name) values ('George Gerschwin');
insert into ARTIST(name) values ('Ludwig van Beethoven');
insert into ARTIST(name) values ('Franz Schubert');
insert into ARTIST(name) values ('Johann Strauss');
insert into ARTIST(name) values ('Karl Maria von Weber');
insert into ARTIST(name) values ('Georges Bizet');
insert into ARTIST(name) values ('Jacques Offenbach');
insert into ARTIST(name) values ('Johann Sebastian Bach');
insert into ARTIST(name) values ('Wolfgang Amadeus Mozart');
insert into ARTIST(name) values ('Maurice Ravel');
insert into ARTIST(name) values ('Richard Wagner');
insert into ARTIST(name) values ('Giuseppe Verdi');
insert into ARTIST(name) values ('Fryderyk Chopin');
insert into ARTIST(name) values ('Joseph Haydn');
insert into ARTIST(name) values ('Elvis Presley');
insert into ARTIST(name) values ('Shocking Blue');
insert into ARTIST(name) values ('Billy Swan');
insert into ARTIST(name) values ('Cher');
insert into ARTIST(name) values ('Billy Joel');
insert into ARTIST(name) values ('Bob Dylan');
insert into ARTIST(name) values ('Queen');
insert into ARTIST(name) values ('Simon and Garfunkel');
insert into ARTIST(name) values ('The Beach Boys');
insert into ARTIST(name) values ('Mammas and Pappas');
insert into ARTIST(name) values ('The Byrds');
insert into ARTIST(name) values ('The Turtles');
insert into ARTIST(name) values ('The Kinks');
insert into ARTIST(name) values ('James Brown');
insert into ARTIST(name) values ('The Surfaris');
insert into ARTIST(name) values ('Jimmy Cliff');
insert into ARTIST(name) values ('Status Quo');
insert into ARTIST(name) values ('Adiemus');
insert into ARTIST(name) values ('Aerosmith');
insert into ARTIST(name) values ('Apocalyptica');
insert into ARTIST(name) values ('Metallica');
insert into ARTIST(name) values ('David Bowie');
insert into ARTIST(name) values ('Coldplay');
insert into ARTIST(name) values ('Cranberries');
insert into ARTIST(name) values ('Dave Mathews Band');
insert into ARTIST(name) values ('Enigma');
insert into ARTIST(name) values ('Enya');
insert into ARTIST(name) values ('Era');
insert into ARTIST(name) values ('Eric Clapton');
insert into ARTIST(name) values ('Jamie Cullum');
insert into ARTIST(name) values ('Jimi Hendrix');
insert into ARTIST(name) values ('Joe Cocker');
insert into ARTIST(name) values ('John Lennon');
insert into ARTIST(name) values ('John Legend');
insert into ARTIST(name) values ('Les Wampas');
insert into ARTIST(name) values ('Indochine');
insert into ARTIST(name) values ('Nightwish');
insert into ARTIST(name) values ('Nouvelle Vague');
insert into ARTIST(name) values ('Oliver Shanti');
insert into ARTIST(name) values ('Pearl Jam');
insert into ARTIST(name) values ('Phil Collins');
insert into ARTIST(name) values ('Phish');
insert into ARTIST(name) values ('Prodigy');
insert into ARTIST(name) values ('R.E.M');
insert into ARTIST(name) values ('Red Hot Chili Peppers');
insert into ARTIST(name) values ('Green Day');
insert into ARTIST(name) values ('Robbie Williams');
insert into ARTIST(name) values ('Morcheeba');
insert into ARTIST(name) values ('Adele');
insert into ARTIST(name) values ('The Velvet Underground');
insert into ARTIST(name) values ('Yoshida Brothers');
insert into ARTIST(name) values ('Dire Straits');
insert into ARTIST(name) values ('Mark Knopfler');
insert into ARTIST(name) values ('Genesis');
insert into ARTIST(name) values ('Yes');

/* Inicializace tabulky Album */
insert into ALBUM(title, released) values ('Yoshida Brothers', 2003);
insert into ALBUM(title, released) values ('Yoshida Brothers II', 2004);
insert into ALBUM(title, released) values ('Animals', 1977);
insert into ALBUM(title, released) values ('Stupid Dream', 1999);
insert into ALBUM(title, released) values ('Close To The Edge', 1981);
insert into ALBUM(title, released) values ('In Absentia ', 2003);
insert into ALBUM(title, released) values ('Signify', 1998);
insert into ALBUM(title, released) values ('The Sky Moves Sideways', 1995);
insert into ALBUM(title, released) values ('Deadwing', 2005);
insert into ALBUM(title, released) values ('Up The Downstair', 2005);
insert into ALBUM(title, released) values ('Tonite Lets All Make Love in London', 1966);
insert into ALBUM(title, released) values ('The Piper At The Gates Of Dawn', 1967);
insert into ALBUM(title, released) values ('A Saucerful Of Secrets', 1968);
insert into ALBUM(title, released) values ('More', 1969);
insert into ALBUM(title, released) values ('Ummagumma', 1969);
insert into ALBUM(title, released) values ('Atom Heart Mother', 1970);
insert into ALBUM(title, released) values ('Zabriskie Point', 1970);
insert into ALBUM(title, released) values ('Dark Side Of The Moon', 1973);
insert into ALBUM(title, released) values ('Wish You Are Here', 1975);
insert into ALBUM(title, released) values ('The Wall', 1979);
insert into ALBUM(title, released) values ('Works', 1983);
insert into ALBUM(title, released) values ('Delicate Sound Of Thunder', 1988);
insert into ALBUM(title, released) values ('The Division Bell', 1992);
insert into ALBUM(title, released) values ('Always Outnumbered Never Outgunned', 2003);
insert into ALBUM(title, released) values ('Cantata Mundi', 1999);
insert into ALBUM(title, released) values ('Songs of Sanctuary', 2002);
insert into ALBUM(title, released) values ('Inquisition Symphony', 1998);
insert into ALBUM(title, released) values ('Worlds Collide', 2007);
insert into ALBUM(title, released) values ('Reflections', 2003);
insert into ALBUM(title, released) values ('Money And Cigarettes', 1983);
insert into ALBUM(title, released) values ('Slowhand', 1977);
insert into ALBUM(title, released) values ('Pilgrim', 1998);
insert into ALBUM(title, released) values ('Rush Of Blood To The Head', 2002);
insert into ALBUM(title, released) values ('X&Y', 2005);
insert into ALBUM(title, released) values ('Without Parachutes', 2000);
insert into ALBUM(title, released) values ('Fire It Up', 2012);
insert into ALBUM(title, released) values ('Hard Knocks', 2010);
insert into ALBUM(title, released) values ('Unchain My Heart', 1987);
insert into ALBUM(title, released) values ('Imagine', 1971);
insert into ALBUM(title, released) values ('Led Zeppelin I', 1969);
insert into ALBUM(title, released) values ('Led Zeppelin II', 1969);
insert into ALBUM(title, released) values ('Led Zeppelin IV', 1971);
insert into ALBUM(title, released) values ('Mothership', 2007);
insert into ALBUM(title, released) values ('In Throught The Out Door', 1979);
insert into ALBUM(title, released) values ('The Hobbit - An Unexpected Journey', 2012);
insert into ALBUM(title, released) values ('The Lord Of The Rings - The Fellowship Of The Ring', 2001);
insert into ALBUM(title, released) values ('The Lord Of The Rings - The Two Towers', 2002);
insert into ALBUM(title, released) values ('The Lord Of The Rings - Return Of The King', 2003);
insert into ALBUM(title, released) values ('The Last Samurai', 2004);
insert into ALBUM(title, released) values ('Stargate', 1994);
insert into ALBUM(title, released) values ('From The New World', 2009);
insert into ALBUM(title, released) values ('Mutter', 2001);
insert into ALBUM(title, released) values ('Reise Reise', 2004);
insert into ALBUM(title, released) values ('Rosenrot', 2005);
insert into ALBUM(title, released) values ('Sehnsucht', 1997);
insert into ALBUM(title, released) values ('Herzeleid', 1995);
insert into ALBUM(title, released) values ('Sounds Of Silence', 1974);
insert into ALBUM(title, released) values ('Morrison Hotel', 1970);
insert into ALBUM(title, released) values ('L.A.Woman', 1971);
insert into ALBUM(title, released) values ('The Doors', 1967);
insert into ALBUM(title, released) values ('The Velvet Underground', 1969);

/* Inicializace tabulky Song */
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Tabidachi', 320, 1, '', (select id from GENRE where name = 'World'), (select id from ALBUM where title = 'Yoshida Brothers'), (select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Hyakka Ryouran (Blooming)', 320, 2,'', (select id from GENRE where name = 'World'), (select id from ALBUM where title = 'Yoshida Brothers'), (select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Madrugada', 320, 3,'',(select id from GENRE where name = 'World'),(select id from ALBUM where title = 'Yoshida Brothers'), (select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Storm', 320, 4,'',(select id from GENRE where name = 'World'),(select id from ALBUM where title = 'Yoshida Brothers'),(select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Namonaki Oka (A Hill with No Name)', 320, 5,'',(select id from GENRE where name = 'World'),(select id from ALBUM where title = 'Yoshida Brothers'),(select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Tsugaru Jyangara Bushi', 320, 6,'',(select id from GENRE where name = 'World'),(select id from ALBUM where title = 'Yoshida Brothers'),(select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Labyrinth (Modern Second Movement)', 320, 7,'',(select id from GENRE where name = 'World'),(select id from ALBUM where title = 'Yoshida Brothers'),(select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Moyuru (Sprouting)', 320, 8,'',(select id from GENRE where name = 'World'),(select id from ALBUM where title = 'Yoshida Brothers'),(select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Fukaki Umi No Kanata', 320, 9,'',(select id from GENRE where name = 'World'),(select id from ALBUM where title = 'Yoshida Brothers'),(select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Tsugaru Jyangara Bushi 2', 320, 10,'',(select id from GENRE where name = 'World'),(select id from ALBUM where title = 'Yoshida Brothers'),(select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Storm (TM Mix)', 320, 11,'',(select id from GENRE where name = 'World'),(select id from ALBUM where title = 'Yoshida Brothers'),(select id from ARTIST where name = 'Yoshida Brothers'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Pigs on the Wing (Part One)', 128, 1,'According to Nick Mason, and confirmed by Waters, it is a love song directed towards Waters new wife at the time, Carolyne. She was really the only one Rogers friends had ever met who could hold her own in an argument with him',(select id from GENRE where name = 'Art Rock'),(select id from ALBUM where title = 'Animals'),(select id from ARTIST where name = 'Pink Floyd'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Dogs',  128, 2,'',(select id from GENRE where name = 'Art Rock'),(select id from ALBUM where title = 'Animals'),(select id from ARTIST where name = 'Pink Floyd'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Pigs (Three Different Ones)', 128, 3,'',(select id from GENRE where name = 'Art Rock'),(select id from ALBUM where title = 'Animals'),(select id from ARTIST where name = 'Pink Floyd'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Sheep', 128, 4,'',(select id from GENRE where name = 'Art Rock'),(select id from ALBUM where title = 'Animals'),(select id from ARTIST where name = 'Pink Floyd'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Pigs on the Wing (Part Two)', 128, 5,'',(select id from GENRE where name = 'Art Rock'),(select id from ALBUM where title = 'Animals'),(select id from ARTIST where name = 'Pink Floyd'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Even Less', 256, 1,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Piano Lessons', 256, 2,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Stupid Dream', 256, 3,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Pure Narcotic', 256, 4,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Slave Called Shiver', 256, 5,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Dont Hate Me', 256, 6,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('This Is No Rehearsal', 256, 7,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Baby Dream In Cellophane', 256, 8,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Stranger By The Minute', 256, 9,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('A Smart Kid', 256, 10,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Tinto Brass', 256, 11,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));
insert into SONG(title, bitrate, position, commentary, genre_id, album_id, artist_id) values ('Stop Swimming', 256, 12,'',(select id from GENRE where name = 'Progressive Rock'),(select id from ALBUM where title = 'Stupid Dream'),(select id from ARTIST where name = 'Porcupine Tree'));