/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pa165.fleetmanagement.rest;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author SOAD
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method. It is automatically
     * re-generated by NetBeans REST support to populate given list with all
     * resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(cz.muni.fi.pa165.fleetmanagement.rest.EmployeeResource.class);
        resources.add(cz.muni.fi.pa165.fleetmanagement.rest.EmployeeServiceResource.class);
        resources.add(cz.muni.fi.pa165.fleetmanagement.rest.ServiceIntervalResource.class);
        resources.add(cz.muni.fi.pa165.fleetmanagement.rest.ServiceIntervalServiceResource.class);
    }
}
